### ISSUE TITLE
Fix apt-get 

### ISSUE THREAD

**Issue by misterbisson** [misterbisson/triton-couchbase#9]
```
# apt-get install htop
E: Dynamic MMap ran out of room. Please increase the size of APT::Cache-Limit. Current value: 25165824. (man 5 apt.conf)
```

@tgross @askfongjojo do you remember the answer to this?

**Comment by askfongjojo** [comment]
@misterbisson - the workaround is to comment out some of the repos in the source list, as described in https://devhub.joyent.com/jira/browse/OS-4751.

**Comment by misterbisson** [comment]
Thank you for the reminder on that jira ticket, @askfongjojo

**Comment by misterbisson** [comment]
This was fixed some time ago. Closing.
